# Render Blueprint for Soundboard App
services:
  # Backend Service (Node.js)
  - type: web
    name: soundboard-backend
    env: node
    buildCommand: |
      echo "Installing dependencies..."
      npm install --prefix server
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NPM_CONFIG_PRODUCTION
        value: 'false'
    plan: free
    region: oregon

  # Frontend Service (Static Site)
  - type: web
    name: soundboard-frontend
    env: static
    buildCommand: |
      echo "Installing frontend dependencies..."
      cd client
      npm install
      npm run build
      echo "Frontend build complete"
    staticPublishPath: ./client/dist
    envVars:
      - key: REACT_APP_API_URL
        value: https://soundboard-backend.onrender.com
