# Render Blueprint for Soundboard App
services:
  # Backend Service
  - type: web
    name: soundboard-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    plan: free

  # Frontend Service
  - type: web
    name: soundboard-frontend
    env: node
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://soundboard-backend.onrender.com
    routes:
      - type: rewrite
        source: '/*'
        destination: '/index.html'
    plan: free
