# Render Blueprint for Soundboard App
services:
  # Backend Service (Node.js)
  - type: web
    name: soundboard-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    plan: free
    region: oregon  # Specify a valid region

  # Frontend Service (Static Site)
  - type: static_site
    name: soundboard-frontend
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    envVars:
      - key: REACT_APP_API_URL
        value: https://soundboard-backend.onrender.com
    region: oregon  # Specify a valid region
